import { Component, OnInit } from '@angular/core';import { ActivatedRoute,Router } from '@angular/router';import { forkJoin } from 'rxjs';import { CrmAccount } from '../../models/crm-account.model';import { CrmLead,LEAD_STATUS_LABELS } from '../../models/crm-lead.model';import { CrmOpportunity } from '../../models/crm-opportunity.model';import { CrmPipelineStage } from '../../models/crm-pipeline-stage.model';import { CrmUser } from '../../models/crm-detail.model';import { CrmPermissionsService } from '../../services/crm-permissions.service';import { CrmService } from '../../services/crm.service';
@Component({selector:'app-crm-lead-detail-page',templateUrl:'./crm-lead-detail-page.component.html',styleUrls:['./crm-lead-detail-page.component.scss']})
export class CrmLeadDetailPageComponent implements OnInit{orgId=this.crm.getOrgIdFromToken();id=Number(this.route.snapshot.paramMap.get('id'));lead?:CrmLead;form?:CrmLead;accounts:CrmAccount[]=[];users:CrmUser[]=[];stages:CrmPipelineStage[]=[];opportunities:CrmOpportunity[]=[];loading=true;editing=false;saving=false;error='';statusLabels=LEAD_STATUS_LABELS;
constructor(private crm:CrmService,private route:ActivatedRoute,private router:Router,public permissions:CrmPermissionsService){}ngOnInit():void{this.load();}
load():void{this.loading=true;forkJoin({lead:this.crm.getLead(this.orgId,this.id),accounts:this.crm.getAccounts(this.orgId),users:this.crm.getCrmUsers(this.orgId),stages:this.crm.getStages(this.orgId),opps:this.crm.getOpportunities(this.orgId,{leadId:this.id})}).subscribe({next:r=>{this.lead=r.lead;this.form={...r.lead};this.accounts=r.accounts;this.users=r.users;this.stages=r.stages;this.opportunities=r.opps;this.loading=false;},error:e=>{this.error=e?.error?.message||'Lead not found.';this.loading=false;}});}
save():void{if(!this.form)return;this.saving=true;this.crm.updateLead(this.orgId,this.id,this.form).subscribe({next:v=>{this.lead=v;this.form={...v};this.editing=false;this.saving=false;},error:e=>{this.error=e?.error?.message||'Unable to save.';this.saving=false;}});}setStatus(status:any):void{if(!this.form||!this.permissions.canWriteCrm)return;this.form.status=status;this.save();}
convert():void{if(!this.permissions.canWriteCrm||this.lead?.converted)return;const stageId=this.stages[0]?.id||null;this.crm.convertLead(this.orgId,this.id,stageId).subscribe({next:o=>this.router.navigate(['/crm/opportunities',o.id]),error:e=>this.error=e?.error?.message||'Unable to convert.'});}
remove():void{if(!confirm('Delete this lead?'))return;this.crm.deleteLead(this.orgId,this.id).subscribe({next:()=>this.router.navigate(['/crm/leads']),error:e=>this.error=e?.error?.message||'Unable to delete.'});}
cancel():void{if(this.lead)this.form={...this.lead};this.editing=false;}initials():string{return(this.lead?.fullName||'?').split(/\s+/).slice(0,2).map(v=>v[0]).join('').toUpperCase();}}
