import { Component,OnInit } from '@angular/core';import { Router } from '@angular/router';import { forkJoin } from 'rxjs';import { CrmAccount } from '../../models/crm-account.model';import { CrmLead } from '../../models/crm-lead.model';import { CrmOpportunity,emptyOpportunity } from '../../models/crm-opportunity.model';import { CrmPipelineStage } from '../../models/crm-pipeline-stage.model';import { CrmSupplyCategory,CrmUser } from '../../models/crm-detail.model';import { CrmPermissionsService } from '../../services/crm-permissions.service';import { CrmService } from '../../services/crm.service';
@Component({selector:'app-crm-opportunities-page',templateUrl:'./crm-opportunities-page.component.html',styleUrls:['./crm-opportunities-page.component.scss']})
export class CrmOpportunitiesPageComponent implements OnInit{orgId=this.crm.getOrgIdFromToken();opportunities:CrmOpportunity[]=[];stages:CrmPipelineStage[]=[];accounts:CrmAccount[]=[];categories:CrmSupplyCategory[]=[];users:CrmUser[]=[];contacts:CrmLead[]=[];loading=true;stageFilter:number|null=null;search='';showForm=false;saving=false;form=emptyOpportunity();error='';
constructor(private crm:CrmService,private router:Router,public permissions:CrmPermissionsService){}ngOnInit():void{forkJoin({stages:this.crm.getStages(this.orgId),accounts:this.crm.getAccounts(this.orgId),categories:this.crm.getSupplyCategories(this.orgId),users:this.crm.getCrmUsers(this.orgId)}).subscribe(v=>{this.stages=v.stages;this.accounts=v.accounts;this.categories=v.categories;this.users=v.users;});this.load();}
load():void{this.loading=true;this.crm.getOpportunities(this.orgId,this.stageFilter?{stageId:this.stageFilter}:{}).subscribe({next:v=>{this.opportunities=v;this.loading=false;},error:e=>{this.error=e?.error?.message||'Unable to load opportunities.';this.loading=false;}});}get filtered():CrmOpportunity[]{const q=this.search.toLowerCase().trim();return q?this.opportunities.filter(o=>o.name.toLowerCase().includes(q)||(o.accountName||'').toLowerCase().includes(q)):this.opportunities;}
setStage(id:number|null):void{this.stageFilter=id;this.load();}open(v:CrmOpportunity):void{this.router.navigate(['/crm/opportunities',v.id]);}openNew():void{this.form=emptyOpportunity();this.form.stageId=this.stages[0]?.id||null;this.showForm=true;this.error='';this.contacts=[];}
accountChanged():void{this.form.leadId=null;this.contacts=[];if(this.form.accountId)this.crm.getLeads(this.orgId,undefined,undefined,this.form.accountId).subscribe(v=>this.contacts=v);}
save():void{if(!this.form.name.trim()||!this.form.accountId){this.error='Opportunity name and Account are required.';return;}this.saving=true;this.crm.createOpportunity(this.orgId,this.form).subscribe({next:v=>{this.saving=false;this.showForm=false;this.router.navigate(['/crm/opportunities',v.id]);},error:e=>{this.error=e?.error?.message||'Unable to create opportunity.';this.saving=false;}});}
money(v:number|null,c='EUR'):string{return v?new Intl.NumberFormat('en',{style:'currency',currency:c,maximumFractionDigits:0}).format(v):'—';}}
