import { Component, OnInit } from '@angular/core';
import { forkJoin, of } from 'rxjs';
import { CrmPipelineStage, emptyStage } from '../../models/crm-pipeline-stage.model';
import { CrmIndustry, CrmNotificationPreference } from '../../models/crm-detail.model';
import { CrmEquipmentType, CrmReportSchedule } from '../../models/crm-equipment.model';
import { CrmPermissionsService } from '../../services/crm-permissions.service';
import { CrmService } from '../../services/crm.service';
import { CrmI18nService } from '../../services/crm-i18n.service';

@Component({ selector: 'app-crm-settings-page', templateUrl: './crm-settings-page.component.html', styleUrls: ['./crm-settings-page.component.scss'] })
export class CrmSettingsPageComponent implements OnInit {
  orgId = this.crm.getOrgIdFromToken(); active: 'pipeline' | 'industry' | 'equipment' | 'schedule' | 'notifications' = 'pipeline'; stages: CrmPipelineStage[] = []; industries: CrmIndustry[] = []; equipmentTypes: CrmEquipmentType[]=[]; schedules: CrmReportSchedule[]=[]; newEquipment: CrmEquipmentType={id:null,code:'',name:'',active:true}; newStage = emptyStage(); newIndustry: CrmIndustry = { id: null, name: '', active: true };
  preferences: CrmNotificationPreference = { emailNotifications: true, stageChangeAlerts: true, closingDateReminders: false };
  addingStage = false; addingIndustry = false; addingEquipment=false; loading = true; savingPreferences = false; error = ''; toast = '';
  readonly reportOptions = [
    { id: 'WORLD_MAP', label: 'settings.reports.WORLD_MAP' }, { id: 'BY_COUNTRY', label: 'settings.reports.BY_COUNTRY' },
    { id: 'TIMELINE', label: 'settings.reports.TIMELINE' }, { id: 'VALUE_SPLIT', label: 'settings.reports.VALUE_SPLIT' },
    { id: 'ERCOPAC_TF', label: 'settings.reports.ERCOPAC_TF' }, { id: 'ERCOPAC_RESALE', label: 'settings.reports.ERCOPAC_RESALE' },
    { id: 'MONTHLY_OVERVIEW', label: 'settings.reports.MONTHLY_OVERVIEW' }, { id: 'CS_PROJECTS', label: 'settings.reports.CS_PROJECTS' },
    { id: 'BP_PROJECTS', label: 'settings.reports.BP_PROJECTS' }, { id: 'EXPECTED_REVENUE', label: 'settings.reports.EXPECTED_REVENUE' },
    { id: 'EQUIPMENT_OVERVIEW', label: 'settings.reports.EQUIPMENT_OVERVIEW' }, { id: 'EQUIPMENT_SHIPMENT_ON_TIME', label: 'settings.reports.EQUIPMENT_SHIPMENT_ON_TIME' }
  ];
  constructor(private crm: CrmService, public permissions: CrmPermissionsService, public i18n: CrmI18nService) {}
  
  ngOnInit(): void { this.load(); }
  
  load(): void { forkJoin({ stages: this.crm.getStages(this.orgId), industries: this.crm.getIndustries(this.orgId, true), equipment:this.crm.getEquipmentTypes(this.orgId,true), schedules:this.permissions.canAccessManagerView?this.crm.getReportSchedules(this.orgId):of([] as CrmReportSchedule[]), preferences: this.crm.getNotificationPreferences(this.orgId) }).subscribe({ next: result => { this.stages = result.stages; this.industries = result.industries; this.equipmentTypes=result.equipment;this.schedules=result.schedules; this.preferences = result.preferences; this.loading = false; }, error: error => { this.error = error?.error?.message || this.i18n.t('settings.error.load'); this.loading = false; } }); }
  
  saveEquipment(item:CrmEquipmentType):void {if(!item.id)return;this.crm.updateEquipmentType(this.orgId,item.id,item).subscribe({next:v=>{Object.assign(item,v);this.flash(this.i18n.t('settings.toast.equipmentSaved'));},error:e=>this.error=e?.error?.message||this.i18n.t('settings.error.saveEquipment')});}
  addEquipment():void {if(!this.newEquipment.code.trim()||!this.newEquipment.name.trim())return;this.crm.createEquipmentType(this.orgId,this.newEquipment).subscribe({next:v=>{this.equipmentTypes=[...this.equipmentTypes,v];this.newEquipment={id:null,code:'',name:'',active:true};this.addingEquipment=false;this.flash(this.i18n.t('settings.toast.equipmentAdded'));},error:e=>this.error=e?.error?.message||this.i18n.t('settings.error.addEquipment')});}
  deleteEquipment(item:CrmEquipmentType):void {if(!item.id||!confirm(this.i18n.t('settings.confirm.deactivateEquipment')))return;this.crm.deleteEquipmentType(this.orgId,item.id).subscribe({next:()=>{item.active=false;this.flash(this.i18n.t('settings.toast.equipmentDeactivated'));},error:e=>this.error=e?.error?.message||this.i18n.t('settings.error.deactivateEquipment')});}
  get activeEquipmentTypes(): CrmEquipmentType[] { return this.equipmentTypes.filter(item => item.active); }
  get activeIndustries(): CrmIndustry[] { return this.industries.filter(item => item.active); }
  startEquipment(): void { this.newEquipment={id:null,code:'',name:'',active:true}; this.addingEquipment=true; }
  startIndustry(): void { this.newIndustry={id:null,name:'',active:true}; this.addingIndustry=true; }
  startStage(): void { this.newStage=emptyStage(); this.newStage.probability=50; this.addingStage=true; }
  addSchedule():void {const dto:CrmReportSchedule={id:null,reportType:'MONTHLY_OVERVIEW',typeFilter:'ALL',recipients:'',frequency:'MONTHLY',active:true,lastSentAt:null,nextRunAt:null};this.schedules=[...this.schedules,dto];}
  saveSchedule(item:CrmReportSchedule):void {if(!this.permissions.canWriteCrm)return;if(!item.recipients.trim()){if(item.id)this.error=this.i18n.t('settings.error.recipientsRequired');return;}this.error='';if(item.id)this.crm.updateReportSchedule(this.orgId,item.id,item).subscribe({next:v=>{Object.assign(item,v);this.flash(this.i18n.t('settings.toast.scheduleSaved'));},error:e=>this.error=e?.error?.message||this.i18n.t('settings.error.saveSchedule')});else this.crm.createReportSchedule(this.orgId,item).subscribe({next:v=>{this.schedules=this.schedules.map(x=>x===item?v:x);this.flash(this.i18n.t('settings.toast.scheduleSaved'));},error:e=>this.error=e?.error?.message||this.i18n.t('settings.error.saveSchedule')});}
  deleteSchedule(item:CrmReportSchedule):void {if(!item.id){this.schedules=this.schedules.filter(x=>x!==item);return;}if(!confirm(this.i18n.t('settings.confirm.removeSchedule')))return;this.crm.deleteReportSchedule(this.orgId,item.id).subscribe({next:()=>this.schedules=this.schedules.filter(x=>x.id!==item.id),error:e=>this.error=e?.error?.message||this.i18n.t('settings.error.removeSchedule')});}
  saveStage(stage: CrmPipelineStage): void { if (!stage.id) return; this.crm.updateStage(this.orgId, stage.id, stage).subscribe({ next: () => this.flash(this.i18n.t('settings.toast.stageSaved')), error: error => this.error = error?.error?.message || this.i18n.t('settings.error.saveStage') }); }
  moveStage(index: number, direction: -1 | 1): void { const target=index+direction;if(target<0||target>=this.stages.length)return;const first=this.stages[index],second=this.stages[target];[first.displayOrder,second.displayOrder]=[second.displayOrder,first.displayOrder];this.stages[index]=second;this.stages[target]=first;if(!first.id||!second.id)return;forkJoin([this.crm.updateStage(this.orgId,first.id,first),this.crm.updateStage(this.orgId,second.id,second)]).subscribe({next:()=>this.flash(this.i18n.t('settings.toast.stageOrderSaved')),error:error=>{this.error=error?.error?.message||this.i18n.t('settings.error.reorderStages');this.load();}}); }
  addStage(): void { if (!this.newStage.name.trim()) return; this.newStage.displayOrder = this.stages.length; this.crm.createStage(this.orgId, this.newStage).subscribe({ next: stage => { this.stages = [...this.stages, stage]; this.newStage = emptyStage(); this.addingStage = false; this.flash(this.i18n.t('settings.toast.stageAdded')); }, error: error => this.error = error?.error?.message || this.i18n.t('settings.error.addStage') }); }
  deleteStage(stage: CrmPipelineStage): void { if (!stage.id || !confirm(this.i18n.t('settings.confirm.deleteStage'))) return; this.crm.deleteStage(this.orgId, stage.id).subscribe({ next: () => this.stages = this.stages.filter(value => value.id !== stage.id), error: error => this.error = error?.error?.message || this.i18n.t('settings.error.deleteStage') }); }
  saveIndustry(industry: CrmIndustry): void { if (!industry.id) return; this.crm.updateIndustry(this.orgId, industry.id, industry).subscribe({ next: value => { Object.assign(industry, value); this.flash(this.i18n.t('settings.toast.industrySaved')); }, error: error => this.error = error?.error?.message || this.i18n.t('settings.error.saveIndustry') }); }
  addIndustry(): void { if (!this.newIndustry.name.trim()) return; this.crm.createIndustry(this.orgId, this.newIndustry).subscribe({ next: value => { this.industries = [...this.industries, value].sort((a, b) => a.name.localeCompare(b.name)); this.newIndustry = { id: null, name: '', active: true }; this.addingIndustry = false; this.flash(this.i18n.t('settings.toast.industryAdded')); }, error: error => this.error = error?.error?.message || this.i18n.t('settings.error.addIndustry') }); }
  deleteIndustry(industry: CrmIndustry): void { if (!industry.id || !confirm(this.i18n.t('settings.confirm.deleteIndustry'))) return; this.crm.deleteIndustry(this.orgId, industry.id).subscribe({ next: () => { this.industries = this.industries.filter(value => value.id !== industry.id); this.flash(this.i18n.t('settings.toast.industryDeleted')); }, error: error => this.error = error?.error?.message || this.i18n.t('settings.error.deleteIndustry') }); }
  savePreferences(): void { if (this.savingPreferences) return; this.savingPreferences = true; this.crm.saveNotificationPreferences(this.orgId, this.preferences).subscribe({ next: value => { this.preferences = value; this.savingPreferences = false; this.flash(this.i18n.t('settings.toast.preferencesSaved')); }, error: error => { this.error = error?.error?.message || this.i18n.t('settings.error.savePreferences'); this.savingPreferences = false; } }); }
  private flash(value: string): void { this.toast = value; setTimeout(() => this.toast = '', 2000); }
}